name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
    - name: Install dependencies
      run: bundle install
    - name: Lint
      run: bundle exec standardrb

