name: Scheduler

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
    - name: Install dependencies
      run: |
        bundle config set --local without 'development test'
        bundle install
    - name: Download products_json
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: true
      with:
        name: products_json
        workflow: schedule.yml
    - name: Execute
      run: bundle exec ruby scripts/main.rb "${ARG}"
      env:
        ARG: products.json
        SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    - name: Save products_json
      uses: actions/upload-artifact@v2
      with:
        name: products_json
        path: products.json
  
